import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import '../styles/globals.css'

export const AuthContext = React.createContext();

function MyApp({ Component, pageProps }) {
  const [user,setUser] = useState(null)

  useEffect(()=>{
    const options = {
      method: 'GET',
      mode: 'same-origin',
      cache: 'no-cache',
      credentials: 'same-origin',
      headers: {
          'Content-Type': 'application/json'
      },
    }
    fetch('/api/user/infos',options)
    .then(res=>res.json())
    .then(data=>setUser(data.user))
  },[])
  return(
    <AuthContext.Provider value={{
        user: user,
        setUserData: (data) => setUser(data)
      }}>
      <div className='app'>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </div>
    </AuthContext.Provider>
  ) 
}

export default MyApp